modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "dragit"
version = "${version}"
displayName = "DragIt"
authors = "Kall"
description = '''
'''
logoFile = "logo.png"